// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyl-M-Rn3-sc4rPQFVmUAgWZ1Cg8TT1EE',
    appId: '1:864339206930:web:2da3c7c1e2e712b70849cb',
    messagingSenderId: '864339206930',
    projectId: 'garagemate-362a6',
    authDomain: 'garagemate-362a6.firebaseapp.com',
    storageBucket: 'garagemate-362a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAYgqFcPr3J0JN2fQLYhRBGOZI8w7Pu-8',
    appId: '1:864339206930:android:4968aa33e841d1800849cb',
    messagingSenderId: '864339206930',
    projectId: 'garagemate-362a6',
    storageBucket: 'garagemate-362a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-cICtwaN77pZkdp_mdCxTkNhY66yB9FM',
    appId: '1:864339206930:ios:ee4ebc50adcc13700849cb',
    messagingSenderId: '864339206930',
    projectId: 'garagemate-362a6',
    storageBucket: 'garagemate-362a6.firebasestorage.app',
    iosBundleId: 'com.example.garageMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-cICtwaN77pZkdp_mdCxTkNhY66yB9FM',
    appId: '1:864339206930:ios:ee4ebc50adcc13700849cb',
    messagingSenderId: '864339206930',
    projectId: 'garagemate-362a6',
    storageBucket: 'garagemate-362a6.firebasestorage.app',
    iosBundleId: 'com.example.garageMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyl-M-Rn3-sc4rPQFVmUAgWZ1Cg8TT1EE',
    appId: '1:864339206930:web:f83b0018f0db99710849cb',
    messagingSenderId: '864339206930',
    projectId: 'garagemate-362a6',
    authDomain: 'garagemate-362a6.firebaseapp.com',
    storageBucket: 'garagemate-362a6.firebasestorage.app',
  );
}
